// Generated by CoffeeScript 1.7.1
var Block,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Block = (function(_super) {
  __extends(Block, _super);

  function Block(display, formula) {
    this.display = display != null ? display : 'basic';
    this.formula = formula;
    Block.__super__.constructor.apply(this, arguments);
  }

  Block.prototype.getHTML = function() {
    return Block.__super__.getHTML.apply(this, arguments);
  };

  Block.prototype.getValue = function() {
    return this.formula.solve();
  };

  Block.prototype.getFormula = function() {
    return this.formula;
  };

  Block.prototype.setFormula = function(formula) {
    this.formula = formula;
  };

  return Block;

})(Element);
