// Generated by CoffeeScript 1.7.1
var Brackets,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Brackets = (function(_super) {
  __extends(Brackets, _super);

  function Brackets(display, formula) {
    this.display = display != null ? display : 'basic';
    this.formula = formula;
    Brackets.__super__.constructor.apply(this, arguments);
  }

  Brackets.prototype.getHTML = function() {
    return $("<span type=\'" + this.display + "\'>(</span>").add(Brackets.__super__.getHTML.apply(this, arguments).addClass('brackets').html(this.formula.display())).add("<span type=\'" + this.display + "\'>)</span>");
  };

  return Brackets;

})(Block);
