// Generated by CoffeeScript 1.7.1
var Constant,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Constant = (function(_super) {
  __extends(Constant, _super);

  function Constant(display, name, value) {
    this.display = display != null ? display : 'basic';
    this.name = name;
    this.value = value;
    Constant.__super__.constructor.apply(this, arguments);
  }

  Constant.prototype.getValue = function() {
    return this.value;
  };

  return Constant;

})(Variable);
