// Generated by CoffeeScript 1.7.1
var Element;

Element = (function() {
  function Element(display) {
    this.display = display != null ? display : 'basic';
    this.next = null;
  }

  Element.prototype.getHTML = function() {
    return $("<span class=\'" + this.display + "\'></span>");
  };

  Element.prototype.getPrevious = function() {
    return this.previous;
  };

  Element.prototype.setPrevious = function(previous) {
    this.previous = previous;
  };

  Element.prototype.getNext = function() {
    return this.next;
  };

  Element.prototype.setNext = function(next) {
    this.next = next;
  };

  Element.prototype.getValue = function() {
    return null;
  };

  Element.prototype.setNextResult = function(nextResult) {
    this.nextResult = nextResult;
  };

  Element.prototype.setPreviousResult = function(previousResult) {
    this.previousResult = previousResult;
  };

  Element.prototype.getNextResult = function() {
    return this.nextResult;
  };

  Element.prototype.getPreviousResult = function() {
    return this.previousResult;
  };

  return Element;

})();
