// Generated by CoffeeScript 1.7.1
var Function,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Function = (function(_super) {
  __extends(Function, _super);

  function Function(display, type) {
    this.display = display != null ? display : 'basic';
    this.type = type;
    Function.__super__.constructor.apply(this, arguments);
    if (!window.HTML_FUNCTIONS.hasOwnProperty(this.type)) {
      throw 'Operand (constructor): wrong type of operand';
    }
  }

  Function.prototype.getHTML = function() {
    return Function.__super__.getHTML.apply(this, arguments).addClass('func').html(window.HTML_FUNCTIONS[this.type]);
  };

  Function.prototype.getValue = function() {
    return this.type;
  };

  return Function;

})(Element);
