// Generated by CoffeeScript 1.7.1
var Init,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Init = (function(_super) {
  __extends(Init, _super);

  function Init() {
    Init.__super__.constructor.call(this, 'init', null);
  }

  Init.prototype.getHTML = function() {
    return null;
  };

  return Init;

})(Element);
