// Generated by CoffeeScript 1.7.1
var NumberObj,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

NumberObj = (function(_super) {
  __extends(NumberObj, _super);

  function NumberObj(display, n) {
    var _ref;
    this.display = display != null ? display : 'basic';
    this.n = n;
    if (!((0 <= (_ref = this.n) && _ref <= 9) || this.n === 'FLOATPOINT')) {
      throw 'number(3): Not number passed to the Number class constructor';
    }
    NumberObj.__super__.constructor.apply(this, arguments);
  }

  NumberObj.prototype.getHTML = function() {
    return NumberObj.__super__.getHTML.apply(this, arguments).html(this.n !== 'FLOATPOINT' ? this.n : ',');
  };

  NumberObj.prototype.getValue = function() {
    return this.n;
  };

  return NumberObj;

})(Element);
