// Generated by CoffeeScript 1.7.1
var Variable,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Variable = (function(_super) {
  __extends(Variable, _super);

  function Variable(display, name, formula) {
    this.display = display != null ? display : 'basic';
    this.name = name;
    this.formula = formula;
    Variable.__super__.constructor.apply(this, arguments);
  }

  Variable.prototype.getHTML = function() {
    return Variable.__super__.getHTML.apply(this, arguments).html(this.name);
  };

  Variable.prototype.getValue = function() {
    return this.formula.solve();
  };

  return Variable;

})(Element);
